### ISSUE TITLE
Wrong Beans init order 

### ISSUE THREAD

**Issue by kevinojt** [citerus/dddsample-core#18]
Spring initializes Beans in declared order.

In DDDSampleApplicationContext.java

“graphTraversalService” should be initialized before "routingService"  because "routingService" requires "graphTraversalService"

"handlingEventFactory" should be initialized before "handlingEventRepository" because "handlingEventRepository" requires "handlingEventFactory"

Or they will just get null pointers.

**Comment by mackos** [comment]
You are correct, thanks!
