### ISSUE TITLE
Why getters from domain classes should not be prefixed with “get” in DDD?

### ISSUE THREAD

**Issue by Kwadz** [citerus/dddsample-core#20]
The DDDSample project seems to be a reference about how to design a DDD project.

I noticed all the getters in the domain classes are not prefixed by `get`. Ex: `Cargo#delivery`

Richard C. Martin, in his book Clean Code, sates:

> Accessors, mutators, and predicates should be named for their value and prefixed with get, set, and is according to the javabean standard.

So, should we avoid to follow his advice in this context? If so, why would it be more important than consistency?

_Copied from [my question on SO.](https://stackoverflow.com/questions/46139501/why-getters-from-domain-classes-should-not-be-prefixed-with-get-in-ddd)_

**Comment by rickardsundin** [comment]
VoiceOfUnreason has provided a nicely worded reply to this query on StackOverflow:
https://stackoverflow.com/a/46141986/2033818
