### ISSUE TITLE
Java 9/10 Support

### ISSUE THREAD

**Issue by misto** [citerus/dddsample-core#31]
To run the project using Java 9 or 10, I had to add the following configuration;

```
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>--add-modules java.xml.bind,java.xml.ws</jvmArguments>
                </configuration>
            </plugin>
```

Unfortunately, this will break Java 8 support.

**Comment by simbo1905** [comment]
Java 11 is the current long term support and Java 15 is the latest. To make this code helpful to the majority of people it should be tracking the latest LTS at the minimum.

**Comment by orende** [comment]
We discussed this today and have decided to upgrade to Java 11. In the future, we'll be sticking to the oldest LTS (based on Oracle's Java compiler) for maximum compatibility. We've added a ticket to do the upgrade to our backlog.
