### ISSUE TITLE
mvn spring-boot:run CommandAcceptanceException

### ISSUE THREAD

**Issue by kyleliu1008** [citerus/dddsample-core#44]
> mvn spring-boot:run
Error: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement

**Comment by HrOice** [comment]
Did you solved it ?

**Comment by orende** [comment]
I'm seeing this error as well, but the application seems to run correctly anyway (test pass and behavior is normal). Still, we will look into it and see if we can figure out why the errors are thrown.
