### ISSUE TITLE
Document project history

### ISSUE THREAD

**Issue by DanilSuits** [citerus/dddsample-core#48]
In the source forge repository, the landing page included this historical item

> This project is a joint effort by Eric Evans' company Domain Language and the Swedish software consulting company Citerus.

This language appears to be missing from this github repository.

It's useful, when providing references to this repository, to be able to point to the documentation of its lineage, which lends some additional weight to this project as an "authority" of how DDD was imagined in the past.

**Comment by ahmetbcakici** [comment]
I agree with that. I was thinking "should I trust the repository to learn DDD practices?" because I had no idea about the history of the project. You should specify this.

**Comment by orende** [comment]
Good point! Have made a PR to address this.
