### ISSUE TITLE
How to build and run this in IntelliJ Idea

### ISSUE THREAD

**Issue by prchristie** [citerus/dddsample-core#52]
This is almost certainly a user error. I haven't used Java that much (never used or even knew about Java EE before looking at this). I have tried for the past few hours to get this to work correctly with no luck. Can you guys please point me in some directions for how to do this please? Thanks.

**Comment by orende** [comment]
To build and run the project, first import the project into Intellij (either Community Edition or Ultimate Edition), then click the Maven tab to the right. In the maven tab, expand the DDDSample/Lifecycle item and click `compile`. This will build the project. After that, press `test` to run all the tests and verify that they work. If they work, you can run the project either by expanding the Maven item named DDDSample/Plugins/spring-boot and clicking `spring-boot:run`.
