### ISSUE TITLE
@WebParam annotation should not be used in implementation class

### ISSUE THREAD

**Issue by benblan** [citerus/dddsample-core#8]
When importing the project code into Eclipse Mars, I have 1 error that says "@WebService annotation contains an endpointInterface attribute. No parameters annotated with @WebParam allowed in implementation class".

This error appears in the HandlingReportServiceImpl class.

**Comment by daneidmark** [comment]
Thank you for the input! The master branch is currently being developed with the goal of modernizing the tech stack. In that process we are about to replace the SOAP interface and that will hopefully resolve the issue. If you are having troubles I suggest that you take a look at the tag dddsample-1.1.0 which is the latest stable version.
