### ISSUE TITLE
Coupling to ORM

### ISSUE THREAD

**Issue by dhasilin** [citerus/dddsample-core#87]
Hello, its more question/suggestion:

Even now you have tickets in trello to fix storing itinerary, also if this was not finalized model but a live one, it would greatly benefit from separation of models and orm. Isn't it?
Also such questions are rised in blog, but not fully explained.
There are many ways, memento/mapstruct... But pros and cons are not always obvious.
It would be cool to have a full example ☺️

**Comment by orende** [comment]
Hello! This is a good question, and one that we've been discussing amongst ourselves every now and then, but we still haven't taken a final decision. We've created a discussion thread for this topic [here](https://github.com/citerus/dddsample-core/discussions/82), could you post your opinions there as input?

**Comment by orende** [comment]
Closing issue, everyone interested is welcome to post further replies in the [discussion thread](https://github.com/citerus/dddsample-core/discussions/82).
